### ISSUE TITLE
Add library to Maven central

### ISSUE THREAD

**Issue by izwanink** [ai212983/android-spinnerwheel#31]
This library would be a great addition to mavencentral so Android studio (Gradle) users can just add something like
"compile 'antistatic:spinnerwheel:+' " to their gradle file. This will increases ease of use and popularity of this library.

I found a guide which shows you how to do that. Im not doing it myself because I don't own the library but I'd really appreciate it if you publish it to maven.

Url to the guide:
http://www.survivingwithandroid.com/2014/05/android-guide-to-publish-aar-to-maven-gradle.html

**Comment by mathieudebrito** [comment]
+1

**Comment by jitpack-io** [comment]
Would be easy to publish on https://JitPack.io. Don't even need to upload anything. All that's needed is a GitHub release of android-spinnerwheel and a build.gradle
