### ISSUE TITLE
Any news about Lollipop?

### ISSUE THREAD

**Issue by Rainer-Lang** [ai212983/android-spinnerwheel#38]

**Comment by GerritHoekstra** [comment]
@ai212983 How is development going? I'm looking forward to see the new spinner wheel.

Some ideas:
- [Ripple Effect](https://raw.githubusercontent.com/traex/RippleEffect/master/demo.gif) on individual items
- Support for issue #24
- Overscoll edge effect 
  - Also support for `colorEdgeEffect` to change the color
- Current selected triangle indicator (see reference image 2)

References how spinnerwheel should look like in Material Design:
![Reference 1](https://d13yacurqjgara.cloudfront.net/users/380805/screenshots/1903238/scroll-animation_dribbble.gif)
([Source](https://dribbble.com/shots/1903238-Activity-tracking-app-dashboard-interaction?list=users&offset=6))

![Reference 2](http://i.stack.imgur.com/MTycm.png)
([Source](http://stackoverflow.com/questions/26357512/custom-horizontal-scroll-view-with-picker))

**Comment by ai212983** [comment]
Hi Gerrit. Nah, no news yet.

Your example is not exactly SpinnerWheel as I see it. Originally SpinnerWheel was supposed to be as advanced version of Android's NumberPicker, with horizontal orientation support and ability to display custom elements, not only numbers.

I do like idea of creating widget more abstract and flexible, allowing stuff like you've posted, but it requires a bit of thinking on my side.
Last few months I fell out of Android development, right now I'm refreshing my memory and learning stuff I've missed. After then, I'll make one more attempt to start with Material Design version.
