### ISSUE TITLE
New wheel should support portrait and landscape orientation.

### ISSUE THREAD

**Issue by Rainer-Lang** [ai212983/android-spinnerwheel#39]
Hi,
could I write ideas in "Issues"?
Should I only use one issue and add ideas in the same issue?

**Comment by ai212983** [comment]
closing this thread, new version features should be kept somewhere else

**Comment by Rainer-Lang** [comment]
Where?

**Comment by ai212983** [comment]
in new repo. 
it will be created later this month

**Comment by Rainer-Lang** [comment]
@ai212983 Thanks.
