### ISSUE TITLE
Library adds unwanted permission READ_PHONE_STATE

### ISSUE THREAD

**Issue by oegono** [ai212983/android-spinnerwheel#42]
Due to the lack of min and targetSdkVersion definition in AndroindManifest.xml the library adds the unwanted permission to apps during the build process.

Here is the debug output of merging Manifests:

> android:uses-permission#android.permission.READ_PHONE_STATE
> IMPLIED from AndroidManifest.xml:2:1 reason: antistatic.spinnerwheel has a targetSdkVersion < 4

**Comment by ai212983** [comment]
That's because library is TOO old. 
Won't-fix unless someone will PR this.
