### ISSUE TITLE
setVisibleItems not working as expected

### ISSUE THREAD

**Issue by NehaParmar** [ai212983/android-spinnerwheel#45]
Hi, First I want to Thank you for such a nice library for Spinner wheel view.
The problem I am facing while implementing is, when I  set VisibleItems to 5 on `WheelVerticalView` , I am able to see 5 items when the view is in scrolling mode. As soon as the scroll finishes, I again see 3 items , rest of the items are not visible. 

Right now the wheel view is like this
![what_iam_getting](https://cloud.githubusercontent.com/assets/5079158/6591897/66dc1b7a-c7ec-11e4-868e-51633e597b90.png)

and I want to be like this,i.e, 5 items should be visible
![what_i_want](https://cloud.githubusercontent.com/assets/5079158/6591921/b048d820-c7ec-11e4-9ebe-b59df17f6761.png)

Can you please help me on this, where I am going wrong ?

**Comment by KayWu** [comment]
I did't find related setting methods in the library but edited the source directly to meet the command.
In AbstractWheelView.java,  change
```
mDimSelectorWheelAnimator = ObjectAnimator.ofFloat(this, PROPERTY_SELECTOR_PAINT_COEFF, 1, 0);
```

to 

```
mDimSelectorWheelAnimator = ObjectAnimator.ofFloat(this, PROPERTY_SELECTOR_PAINT_COEFF, 1, 0.3f);
```

**Comment by TigerSkinCat** [comment]
I think it's a bug in WheelVerticalView

**Comment by ai212983** [comment]
not quite remember right now (gotta take a closer look), but i believe KayWu is right. 
This is due to hardcoded painting coefficients, so you have to tweak code himself. 
I'd recommended to try his suggestion.
