### ISSUE TITLE
cannot resolve Gradle dependency 

### ISSUE THREAD

**Issue by rejochandran** [ai212983/android-spinnerwheel#53]
Hi!
I added the gradle dependency as - compile 'com.github.ai212983:android-spinnerwheel:bba368d940' but it doesn't seems to work, it gives a "Failed to resolve error"

Please do help with the issue, Thanks!

**Comment by tompad2** [comment]
+1

**Comment by KayWu** [comment]
+1

**Comment by ai212983** [comment]
This library is pretty old and was written before gradle support in android. Any pull request to implement it will be greatly appreciated though.

**Comment by rejochandran** [comment]
Yup !

**Comment by ai212983** [comment]
JitPack.io kindly added pull request (which I approved) to support gradle/maven, so you're free to try.
This weekend I'll try to add release to enable versioning.

**Comment by rejochandran** [comment]
That's great news ! will try !
