### ISSUE TITLE
Define increments

### ISSUE THREAD

**Issue by pellyadolfo** [ai212983/android-spinnerwheel#55]
Hi, is it possible to increment the wheel on a predefined amount? 

For example, instead of 1,2,3... if I define increments: 5, it should show 5, 10, 15..

This is a really useful component, hopefully development keeps on

**Comment by tompad2** [comment]
I'm not an expert but I think you can do it by an array with just the numbers/text you want, I managed to set it to 1, 2, 3, 4, 5, 10, 15, 20, 25 etc.

**Comment by pellyadolfo** [comment]
but then it would be limited to a subset of numbers....

**Comment by tompad2** [comment]
Hmm I am not sure what you are looking for......any code??

**Comment by GerritHoekstra** [comment]
You can try this:

```java
public int[] range(int start, int end, int step) {
    int n = (int) Math.ceil((end-start)/(double)step);
    int[] arange = new int[n];
    for (int i = 0; i < n; i++)
        arange[i] = i*step+start;
    return arange;
}
```
And then for example: 
```java
int[] range = range(5, 50, 5);
System.out.println(Arrays.toString(range));
```
This would return: `[5, 10, 15, 20, 25, 30, 35, 40, 45]`

**Comment by pellyadolfo** [comment]
Hi, sorry, as the project is not very dynamic now, i missed your responses. Sorry about that.

A sample code could be this wheel defined in a layout.xml

                <com.myapplication.util.spinnerwheel.WheelHorizontalView
                    xmlns:app="http://schemas.android.com/apk/res-auto"
                    android:id="@+id/wheel"
                    android:layout_width="0dp"
                    android:layout_weight="3"
                    android:layout_height="match_parent"
                    android:background="@drawable/button_selected_medium"
                    app:visibleItems="2"
                    android:visibility="gone"/>

and in the Java code:

            final AbstractWheel from = (AbstractWheel) findViewById(R.id.wheel);
            NumericWheelAdapter fromAdapter = new NumericWheelAdapter(this, 100, 300, "%02d");
            fromAdapter.setItemResource(R.layout.wheel_text_centered);
            fromAdapter.setItemTextResource(R.id.text);
            from.setViewAdapter(fromAdapter);

I would expect in the numeric adapter an option to increment the wheel by steps. The problem is that my wheels can range thousands and navigating item by item can be a bad user experience. I do not think is a good idea hardcoding the array number.

* e.g. in Java: 
new NumericWheelAdapter(this, 100, 300, 5, "%02d"); being the 4th argument the step increase

* e.g. in XML:
android:increment="5"

Another thing I would like is to speed up the spinning speed of the items so i simple scroll progresses a larger number of items.

I have been browsing the code and both task looks complex to implement.

**Comment by pellyadolfo** [comment]
I hacked by adding an increment variable to methods of NumericWheelAdapter.

    @Override
    public CharSequence getItemText(int index) {
        if (index >= 0 && index < getItemsCount()) {
            int value = (minValue + index) * increment;
            return format != null ? String.format(format, value) : Integer.toString(value);
        }
        return null;
    }

    @Override
    public int getItemsCount() {
        return (maxValue - minValue + 1) / increment;
    }
