### ISSUE TITLE
define style for current item

### ISSUE THREAD

**Issue by AhmadVatani** [ai212983/android-spinnerwheel#61]
hi
how can i define different style for current item? 
for example i want to change color and size of current item.
tnx

**Comment by arshu-dev** [comment]
close #60 

I got the solution on my own.

Just need to edit the file "AbstractWheelTextAdapter.java" at line number 47.
public static final int DEFAULT_TEXT_COLOR = 0xFF101010;

In this file you can customise the whole style of the wheel & also apply custom text fonts too.

**Comment by fakir22** [comment]
I had the same question. You solution works like a charm, thanks arshu-dev ;)
