### ISSUE TITLE
sample not building straightaway in android studio

### ISSUE THREAD

**Issue by kunalseedoc** [ai212983/android-spinnerwheel#62]
dependency is not resolved

10-30 18:33:06.314 21180-21180/? E/AndroidRuntime: FATAL EXCEPTION: main
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime: Process: antistatic.spinnerwheel.demo, PID: 21180
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{antistatic.spinnerwheel.demo/antistatic.spinnerwheel.demo.ProgrammaticSwitchingActivity}: android.view.InflateException: Binary XML file line #25: Error inflating class antistatic.spinnerwheel.WheelVerticalView
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2314)
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2388)
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.app.ActivityThread.access$800(ActivityThread.java:148)
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1292)
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135)
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5312)
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:  Caused by: android.view.InflateException: Binary XML file line #25: Error inflating class antistatic.spinnerwheel.WheelVerticalView
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.view.LayoutInflater.createView(LayoutInflater.java:633)
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:377)
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.app.Activity.setContentView(Activity.java:2154)
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at antistatic.spinnerwheel.demo.ProgrammaticSwitchingActivity.onCreate(ProgrammaticSwitchingActivity.java:20)
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:5953)
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1128)
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2267)
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2388) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.app.ActivityThread.access$800(ActivityThread.java:148) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1292) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5312) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:  Caused by: java.lang.reflect.InvocationTargetException
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at java.lang.reflect.Constructor.newInstance(Native Method)
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.view.LayoutInflater.createView(LayoutInflater.java:607)
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:377) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.app.Activity.setContentView(Activity.java:2154) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at antistatic.spinnerwheel.demo.ProgrammaticSwitchingActivity.onCreate(ProgrammaticSwitchingActivity.java:20) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:5953) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1128) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2267) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2388) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.app.ActivityThread.access$800(ActivityThread.java:148) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1292) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5312) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:  Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/nineoldandroids/animation/ObjectAnimator;
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at antistatic.spinnerwheel.AbstractWheelView.initData(AbstractWheelView.java:167)
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at antistatic.spinnerwheel.AbstractWheel.<init>(AbstractWheel.java:126)
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at antistatic.spinnerwheel.AbstractWheelView.<init>(AbstractWheelView.java:139)
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at antistatic.spinnerwheel.WheelVerticalView.<init>(WheelVerticalView.java:89)
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at antistatic.spinnerwheel.WheelVerticalView.<init>(WheelVerticalView.java:78)
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at java.lang.reflect.Constructor.newInstance(Native Method) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.view.LayoutInflater.createView(LayoutInflater.java:607) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:377) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.app.Activity.setContentView(Activity.java:2154) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at antistatic.spinnerwheel.demo.ProgrammaticSwitchingActivity.onCreate(ProgrammaticSwitchingActivity.java:20) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:5953) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1128) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2267) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2388) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.app.ActivityThread.access$800(ActivityThread.java:148) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1292) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5312) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.nineoldandroids.animation.ObjectAnimator" on path: DexPathList[[zip file "/data/app/antistatic.spinnerwheel.demo-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at antistatic.spinnerwheel.AbstractWheelView.initData(AbstractWheelView.java:167) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at antistatic.spinnerwheel.AbstractWheel.<init>(AbstractWheel.java:126) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at antistatic.spinnerwheel.AbstractWheelView.<init>(AbstractWheelView.java:139) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at antistatic.spinnerwheel.WheelVerticalView.<init>(WheelVerticalView.java:89) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at antistatic.spinnerwheel.WheelVerticalView.<init>(WheelVerticalView.java:78) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at java.lang.reflect.Constructor.newInstance(Native Method) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.view.LayoutInflater.createView(LayoutInflater.java:607) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:377) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.app.Activity.setContentView(Activity.java:2154) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at antistatic.spinnerwheel.demo.ProgrammaticSwitchingActivity.onCreate(ProgrammaticSwitchingActivity.java:20) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:5953) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1128) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2267) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2388) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.app.ActivityThread.access$800(ActivityThread.java:148) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1292) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5312) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696) 
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:  Suppressed: java.lang.ClassNotFoundException: com.nineoldandroids.animation.ObjectAnimator
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at java.lang.Class.classForName(Native Method)
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:          ... 32 more
10-30 18:33:06.314 21180-21180/? E/AndroidRuntime:  Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by sariego** [comment]
hey,

replace
```java
dependencies {
    provided files('libs/nineoldandroids-2.2.0.jar')
}
```
with
```java
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
}
```
in <b>library/build.grade</b>

there seems to be a problem with the <i>provided</i> directive

Hope it helps

**Comment by sirvanparaste** [comment]
I have the same problem, the above solution did not work for me. 
 I relace that with the following line and is ok now :+1: 

dependencies {
   
    compile 'com.nineoldandroids:library:2.4.0'
}

**Comment by ai212983** [comment]
This library is VERY old and should be rewritten from the scratch, frankly.
So, closing as wont-fix.
