### ISSUE TITLE
On start scroll to item

### ISSUE THREAD

**Issue by octavianmiu** [ai212983/android-spinnerwheel#63]
Hello,

I am trying to make the spinner to scroll to the desired item when app starts. I am using scroll(int item , int time), setCurrentItem(int ibj, int boolean) but nothing happens. Do you have any idea where the problem is?

**Comment by ebadali** [comment]
Wel, you can always use ScrollTo(x,y).
In your case you might want to calculate the vertical position of the desired item. 

mScrollView.post(new Runnable() { 
        public void run() { 
             mScrollView.scrollTo(0, mScrollView.getBottom());
        } 
});

Hope this will help.
