### ISSUE TITLE
i made i a fancy look in my fork

### ISSUE THREAD

**Issue by amorenew** [ai212983/android-spinnerwheel#70]
check this image
![device-2016-08-23-104102](https://cloud.githubusercontent.com/assets/2842459/17883982/51d1dc54-691e-11e6-97c1-130f3e899e96.png)

**Comment by amorenew** [comment]
my fork
https://github.com/amorenew/android-spinnerwheel

**Comment by amorenew** [comment]
XML Attrs
           app:value="1"
            app:minValue="1"
            app:maxValue="12"
            app:pickerTitle="Child Age"
            app:visibleItemsCount="3"
            app:pickerBackground="#fcfcfc"
            app:pickerTextColor="#444"
            app:pickerTitleBackground="#FAFAFA"
            app:pickerTitleTextSize="15dp"
            app:pickerTitleTextColor="#333"

**Comment by bhavikgandhi007** [comment]
is that possible selected color change,or selected item background change
like:
![1](https://cloud.githubusercontent.com/assets/17428508/19033164/ae9ed3b6-897a-11e6-913f-cc26de0ae36a.JPG)

**Comment by amorenew** [comment]
in my fork i added change text color
<attr name="pickerTextColor" format="color" />
https://github.com/amorenew/android-spinnerwheel/blob/master/library/src/main/res/values/attrs.xml

**Comment by bhavikgandhi007** [comment]
i want to change different textcolor for selected valuw and unselected value

**Comment by ai212983** [comment]
As long it's not PR, closing this ticket =)
