### ISSUE TITLE
How to adjust dim the items above and below active item

### ISSUE THREAD

**Issue by nguyencongbinh** [ai212983/android-spinnerwheel#73]
Thank you for your awesome lib.

Please view the image
![wheel](https://cloud.githubusercontent.com/assets/14269299/19682375/7fd43f80-9ad7-11e6-8dee-2f2b7cd26df0.png)

I want to make the item "Montreal" and "Winnipeg" have the same dim ratio with item "Windsor" vs "Edmonton". Where I can modify to achieve this ?

**Comment by ai212983** [comment]
please see suggestion here https://github.com/ai212983/android-spinnerwheel/issues/45
